# Update all the sections by editing the data.yml file inside _data folder.

# Site Settings

# SEO plugin
title: My Resume
author: Guillaume Lhermenier
tagline: SRE # Short description for jekyll-seo-tag
description: giom-l resume # Longer description for jekyll-seo-tag

url: "https://giom-l.github.io"
baseurl: "/cv" # change it according to your repository name

social:
  links:
    - https://www.linkedin.com/in/guillaumelhermenier/
    - https://github.com/giom-l

google_site_verification: # Put your google verification tag here

# End SEO

# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: gray # gray blue turquoise green berry red

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
